# Generated by Django 3.0.6 on 2020-05-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
